### ISSUE TITLE
Provide way to disable auto save for .Batch Rename.txt

### ISSUE THREAD

**Issue by ypresto** [JannisX11/batch-rename#2]
It's just plain text so I could not add per-language settings like below:

```json
  "[batch-renamer]": {
    "files.autoSave": "off"
  },
```

**Comment by ueoo** [comment]
Upvote for this feature.

**Comment by iskandersierra** [comment]
Maybe, instead of using `onDidSaveTextDocument` [here](https://github.com/JannisX11/batch-rename/blob/main/src/extension.ts#L64), you could use `onDidCloseTextDocument`, so that only when the document is closed, the rename takes action.

Currently I have to do a quick edit, or edit the content in a new file, and then copy the changes back to the rename document. Otherwise it closes on its own and apply whatever changes I managed to cramp within a second.

I haven't tried this suggestion, let me know if I can help with it
