### ISSUE TITLE
Publish batch-rename to Open VSX

### ISSUE THREAD

**Issue by omhomurlu** [JannisX11/batch-rename#8]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by stocyr** [comment]
I tried to publish it using their automatic pipeline. However, there are some build errors that I fixed in [this PR](https://github.com/JannisX11/batch-rename/pull/14).

**Comment by stocyr** [comment]
This extension is now published: https://open-vsx.org/extension/JannisX11/batch-rename-extension

**Comment by karlhorky** [comment]
@omhomurlu now that the extension has been published, should this issue be closed?

**Comment by omhomurlu** [comment]
Yes, thank you!

**Comment by karlhorky** [comment]
Ok, great, if you or @JannisX11 could close it, then that would be good 👍

**Comment by djedu28** [comment]
Unfortunately, the provided link doesn't work, and worse: the extension has a clone published by a third party where the code has been slightly modified.

https://github.com/DrInfinite/batch-rename

Since the name and logo are identical to the original (from this repository), it misleads less attentive users into downloading the clone extension. This represents a security vulnerability that allows a malicious extension to be used in a supply chain attack.

----

Automatically translated.

<details><summary>original text in Brazilian Portuguese</summary>

Infelizmente o link fornecido não funciona, e pior: a extensão possui um clone publicado por terceiros onde o código foi ligeiramente modificado

https://github.com/DrInfinite/batch-rename

Como o nome e logo são idênticos ao original (deste repositório), enviesa o usuário menos atento a baixar a extensão clone. Sendo uma brecha de segurança a uma extensão maliciosa em um ataque a cadeia de suprimentos.

</details>
